baseurl = "http://tatamo.github.io/blog/public/"
languageCode = "ja"
title = "わたしろぐ"
canonifyurls = true
rssuri = "rss.xml"

[params]
author = "Tatamo"
description = "Tatamo's weblog"
twitter_url = "https://twitter.com/__tatamo__"
github_url = "https://github.com/tatamo"
copyright_since = "2015"
copyright_latest = "2015"
