baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "ja"
title = "わたしろぐ"

[params]
author = "Tatamo"
description = "Tatamo's weblog"
twitter_url = "https://twitter.com/__tatamo__"
github_url = "https://github.com/tatamo"
